#!/bin/sh

aws s3 --profile mitmproxy cp ./assets/index.html s3://snapshots.mitmproxy.org/
aws s3 --profile mitmproxy cp ./assets/list.js s3://snapshots.mitmproxy.org/
aws s3 --profile mitmproxy cp ./assets/index.html s3://snapshots.mitmproxy.org/error.html
aws --profile mitmproxy \
    cloudfront create-invalidation --distribution-id E2JOW7X9ZEK7GJ --paths "/*"